### ISSUE TITLE
modify Node in place

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaData/XML.jl#11]
Can I update the attributes of a `Node` inplace?

**Comment by joshday** [comment]
Yes!  e.g. `node.attributes[key] = value`

**Comment by joshday** [comment]
I should also say the `node.attributes` could be `nothing` so you'd also need to handle that case.

**Comment by guo-yong-zhi** [comment]
Would you like to add an interface `setattribute!(n::Node, value, key)`?
If you want, I can make a PR.

**Comment by joshday** [comment]
I just added `getindex`/`setindex!` methods with strings to get/set attributes:

```Julia
julia> o = XML.Element("tag")
Node Element <tag>

julia> o["id"] # nothing

julia> o["id"] = 1
1

julia> o["id"]
"1"
```

**Comment by guo-yong-zhi** [comment]
Should we let `o["id"] = nothing` delete the key in attribute Dict? It makes the interface invertible and consistent.

**Comment by joshday** [comment]
I think I'd prefer to add a `delete!(::Node, ::String)` method, but I can add that

**Comment by guo-yong-zhi** [comment]
If so, `o["id"]` should raise an error instead of return nothing. Now I think this plan is better. btw, I have an obsession with consistency, haha.

**Comment by guo-yong-zhi** [comment]
And Base.in or haskey should be defined at the same time to make the existence check possible

**Comment by joshday** [comment]
> o["id"] should raise an error instead of return nothing

Agreed. That's been changed.

And I've added `haskey`
