### ISSUE TITLE
missing support for sorted attributes

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaData/XML.jl#14]
This request and its solution are presented [here, in discourse](https://discourse.julialang.org/t/sorted-attributes-in-xml-jl/100168).
Using an ordered dictionary (preferably [Dictionary](https://github.com/andyferris/Dictionaries.jl)) would maintain the order of attributes.

The use case:
- Suppose I have an XML tag: <point x=0 y=0 z=0/>
     - The x, y, and z attributes are ordered; this helps when editing point data.

```
julia> using XML
julia> xyz  = XML.Element("point", x=1, y=2, z=3)
  Node Element <point x="1" z="3" y="2">
```  
_`xyz` does not remain `x, y, z` ordered_

**Comment by joshday** [comment]
Thanks for the issue.  I do plan on making attributes ordered!

I will likely add a type parameter and default to `OrderedDict`.

**Comment by AhmedSalih3d** [comment]
> Thanks for the issue. I do plan on making attributes ordered!
> 
> I will likely add a type parameter and default to `OrderedDict`.

Thank you! That sounds really great, looking forward to try that when it goes into live :)

**Comment by joshday** [comment]
The type parameter added too much complexity for my taste.  Instead `OrderedDict` is now baked in.
