### ISSUE TITLE
Overload `keys`?

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/XML.jl#26]
I had been wondering what my `Node` contained.
I figured since this package supports `getindex` it would also support keys.
But that method errors:

```julia-repl
julia> ann = parse(Node, ann_str)
Node Document (1 child)

julia> keys(ann)
ERROR: MethodError: no method matching keys(::Node)
```

**Comment by joshday** [comment]
Fixed on master!  New release momentarily
