### ISSUE TITLE
Empty first line

### ISSUE THREAD

**Issue by kezkankrayon** [JuliaData/XML.jl#28]
The `XML.write(path, doc)` method appears to write an empty first line before opening the xml tag.

**Comment by joshday** [comment]
I cannot reproduce this.

**Comment by kezkankrayon** [comment]
Thank you for looking into this issue.

I found what was causing what appeared to be a blank line. 
My document node picked up some invisible text from somewhere.

```bash
julia> children(doc)
3-element Vector{Node}:
 Node Text "\ufeff"
 Node Declaration <?xml version="1.0" encoding="utf-8"?>
 Node Element <premises group="all"> (300910 children)
```

When removing the text node, the written XML appears as expected.
