### ISSUE TITLE
Limit `show` output

### ISSUE THREAD

**Issue by rafaqz** [JuliaData/XML.jl#6]
I just opened an SVG with `XML.Document` and had a flooded REPL I had to Ctrl-C out of.

(Otherwise this seems awesome, would be nice to have native SVG.jl built on this that converts to GeometryBasics.jl objects or something)

**Comment by joshday** [comment]
I just pushed a change so that `XML.Document` won't print the root node.  I'll get a new release out soon.

I've thought about doing an SVG package based on `Cobweb.Node`s (https://github.com/JuliaComputing/Cobweb.jl).  I really like the syntax of `Cobweb.h` I came up with in there.
