### ISSUE TITLE
streaming?

### ISSUE THREAD

**Issue by Moelf** [JuliaData/XML.jl#8]
sometimes we have big XML files, for example: https://juliaio.github.io/EzXML.jl/latest/manual/#Streaming-API-1

**Comment by joshday** [comment]
This would be a little work to hack together but there's already the machinery in here for efficiently iterating through an XML file.  I won't have time to work on it in the near future but I'll put it on the back burner.

**Comment by joshday** [comment]
XML.jl now immediately mmaps the input file.  Along with the `LazyNode` iterator, is this sufficient to handle your use case?

**Comment by joshday** [comment]
FWIW I tested a few parsing implementations before landing on what's now in here, and the mmap version was faster than working with an `IOStream` (at least for smallish datasets).
