### ISSUE TITLE
handle `.gz` or similarly compressed file

### ISSUE THREAD

**Issue by Moelf** [JuliaData/XML.jl#9]
https://github.com/JuliaComputing/XML.jl/blob/e998078b61e72ad3f617e80118674b534402f804/src/XML.jl#L253

adaopting this to
```julia
using CodecZlib
open(io -> Document(XMLTokenIterator(GzipDecompressorStream(io))), file, "r")
```

doesn't work

**Comment by Moelf** [comment]
[books.xml.gz](https://github.com/JuliaComputing/XML.jl/files/11183921/books.xml.gz)
```julia
julia> using XML, CodecZlib
[ Info: Precompiling XML [72c71f33-b9b6-44de-8c94-c961784809e2]

julia> open(io -> Document(XML.XMLTokenIterator(GzipDecompressorStream(io))), "./test/books.xml.gz", "r")
ERROR: MethodError: no method matching seek(::TranscodingStreams.TranscodingStream{GzipDecompressor, IOStream}, ::Int64)
```

**Comment by joshday** [comment]
Hmm, is there reason that `Base.seek` method is missing?

**Comment by joshday** [comment]
I guess so:

https://github.com/JuliaIO/CodecZlib.jl/issues/7#issuecomment-331077954

When I have time, I'll look into a workaround

**Comment by joshday** [comment]
Oh, I think there's a relatively easy fix:  Change `seek` to `seekstart` if the starting position is one.  I'll try it out this week.

**Comment by Moelf** [comment]
yeah I would think for reading an XML you don't need `seek` random positions

**Comment by joshday** [comment]
I'm going to close this for now and state that the "official" way to read a compressed file is to decompress it.  I would entertain PRs that implement it, however.
